/** Écrans de l'admin d'une commune, avec les données du mock (e2e/api.ts) : balayages communs */
export const ROUTES = [
  '/',
  '/pages',
  '/pages/p-salle',
  '/actualites',
  '/actualites/a-conseil',
  '/agenda',
  '/agenda/e-fete',
  '/documents',
  '/documents/nouvelle',
  '/equipe',
  '/associations',
  '/associations?onglet=propositions',
  '/alertes',
  '/alertes/nouvelle',
  '/dechets',
  '/cantine?semaine=2026-09-21',
  '/messages',
  '/messages?id=m-dubois',
  '/newsletter',
  '/mediatheque',
  '/mon-site/menu',
  '/mon-site/apparence',
  '/mon-site/accueil',
  '/mon-site/informations',
  '/mon-site/legal',
  '/mon-site/accessibilite',
  '/mon-site/reseaux',
  '/mon-site/demarches',
  '/mon-site/open-data',
  '/mise-en-ligne',
  '/conformite',
  '/utilisateurs',
  '/mon-compte',
];

/** Espace de l'équipe Communeo (super admin) */
export const PLATFORM_ROUTES = [
  '/plateforme',
  '/plateforme/communes/site-bellefontaine',
  '/plateforme/utilisateurs',
  '/plateforme/statistiques',
];
