/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CommunesRouteImport } from './routes/communes'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as NouveauMotDePasseRouteImport } from './routes/nouveau-mot-de-passe'
import { Route as PlateformeRouteImport } from './routes/plateforme'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActualitesRouteImport } from './routes/_app/actualites'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAlertesRouteImport } from './routes/_app/alertes'
import { Route as AppAssociationsRouteImport } from './routes/_app/associations'
import { Route as AppCantineRouteImport } from './routes/_app/cantine'
import { Route as AppComposantsRouteImport } from './routes/_app/composants'
import { Route as AppConformiteRouteImport } from './routes/_app/conformite'
import { Route as AppDechetsRouteImport } from './routes/_app/dechets'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppEditeurDeBlocsRouteImport } from './routes/_app/editeur-de-blocs'
import { Route as AppEquipeRouteImport } from './routes/_app/equipe'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppMediathequeRouteImport } from './routes/_app/mediatheque'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMiseEnLigneRouteImport } from './routes/_app/mise-en-ligne'
import { Route as AppMonCompteRouteImport } from './routes/_app/mon-compte'
import { Route as AppNewsletterRouteImport } from './routes/_app/newsletter'
import { Route as AppPagesRouteImport } from './routes/_app/pages'
import { Route as AppUtilisateursRouteImport } from './routes/_app/utilisateurs'
import { Route as PlateformeIndexRouteImport } from './routes/plateforme/index'
import { Route as PlateformeJournalRouteImport } from './routes/plateforme/journal'
import { Route as PlateformeStatistiquesRouteImport } from './routes/plateforme/statistiques'
import { Route as PlateformeUtilisateursRouteImport } from './routes/plateforme/utilisateurs'
import { Route as AppActualitesDocumentIdRouteImport } from './routes/_app/actualites_.$documentId'
import { Route as AppAgendaDocumentIdRouteImport } from './routes/_app/agenda_.$documentId'
import { Route as AppAlertesDocumentIdRouteImport } from './routes/_app/alertes_.$documentId'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/_app/documents_.$documentId'
import { Route as AppMonSiteAccessibiliteRouteImport } from './routes/_app/mon-site/accessibilite'
import { Route as AppMonSiteAccueilRouteImport } from './routes/_app/mon-site/accueil'
import { Route as AppMonSiteApparenceRouteImport } from './routes/_app/mon-site/apparence'
import { Route as AppMonSiteDemarchesRouteImport } from './routes/_app/mon-site/demarches'
import { Route as AppMonSiteInformationsRouteImport } from './routes/_app/mon-site/informations'
import { Route as AppMonSiteLegalRouteImport } from './routes/_app/mon-site/legal'
import { Route as AppMonSiteMenuRouteImport } from './routes/_app/mon-site/menu'
import { Route as AppMonSiteOpenDataRouteImport } from './routes/_app/mon-site/open-data'
import { Route as AppMonSiteReseauxRouteImport } from './routes/_app/mon-site/reseaux'
import { Route as AppPagesDocumentIdRouteImport } from './routes/_app/pages_.$documentId'
import { Route as PlateformeCommunesDocumentIdRouteImport } from './routes/plateforme/communes.$documentId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunesRoute = CommunesRouteImport.update({
  id: '/communes',
  path: '/communes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveauMotDePasseRoute = NouveauMotDePasseRouteImport.update({
  id: '/nouveau-mot-de-passe',
  path: '/nouveau-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateformeRoute = PlateformeRouteImport.update({
  id: '/plateforme',
  path: '/plateforme',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActualitesRoute = AppActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertesRoute = AppAlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => AppRoute,
} as any)
const AppAssociationsRoute = AppAssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => AppRoute,
} as any)
const AppCantineRoute = AppCantineRouteImport.update({
  id: '/cantine',
  path: '/cantine',
  getParentRoute: () => AppRoute,
} as any)
const AppComposantsRoute = AppComposantsRouteImport.update({
  id: '/composants',
  path: '/composants',
  getParentRoute: () => AppRoute,
} as any)
const AppConformiteRoute = AppConformiteRouteImport.update({
  id: '/conformite',
  path: '/conformite',
  getParentRoute: () => AppRoute,
} as any)
const AppDechetsRoute = AppDechetsRouteImport.update({
  id: '/dechets',
  path: '/dechets',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEditeurDeBlocsRoute = AppEditeurDeBlocsRouteImport.update({
  id: '/editeur-de-blocs',
  path: '/editeur-de-blocs',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppMediathequeRoute = AppMediathequeRouteImport.update({
  id: '/mediatheque',
  path: '/mediatheque',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMiseEnLigneRoute = AppMiseEnLigneRouteImport.update({
  id: '/mise-en-ligne',
  path: '/mise-en-ligne',
  getParentRoute: () => AppRoute,
} as any)
const AppMonCompteRoute = AppMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsletterRoute = AppNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AppRoute,
} as any)
const AppPagesRoute = AppPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilisateursRoute = AppUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AppRoute,
} as any)
const PlateformeIndexRoute = PlateformeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlateformeRoute,
} as any)
const PlateformeJournalRoute = PlateformeJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => PlateformeRoute,
} as any)
const PlateformeStatistiquesRoute = PlateformeStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => PlateformeRoute,
} as any)
const PlateformeUtilisateursRoute = PlateformeUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => PlateformeRoute,
} as any)
const AppActualitesDocumentIdRoute = AppActualitesDocumentIdRouteImport.update({
  id: '/actualites_/$documentId',
  path: '/actualites/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaDocumentIdRoute = AppAgendaDocumentIdRouteImport.update({
  id: '/agenda_/$documentId',
  path: '/agenda/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertesDocumentIdRoute = AppAlertesDocumentIdRouteImport.update({
  id: '/alertes_/$documentId',
  path: '/alertes/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/documents_/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteAccessibiliteRoute = AppMonSiteAccessibiliteRouteImport.update({
  id: '/mon-site/accessibilite',
  path: '/mon-site/accessibilite',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteAccueilRoute = AppMonSiteAccueilRouteImport.update({
  id: '/mon-site/accueil',
  path: '/mon-site/accueil',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteApparenceRoute = AppMonSiteApparenceRouteImport.update({
  id: '/mon-site/apparence',
  path: '/mon-site/apparence',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteDemarchesRoute = AppMonSiteDemarchesRouteImport.update({
  id: '/mon-site/demarches',
  path: '/mon-site/demarches',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteInformationsRoute = AppMonSiteInformationsRouteImport.update({
  id: '/mon-site/informations',
  path: '/mon-site/informations',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteLegalRoute = AppMonSiteLegalRouteImport.update({
  id: '/mon-site/legal',
  path: '/mon-site/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteMenuRoute = AppMonSiteMenuRouteImport.update({
  id: '/mon-site/menu',
  path: '/mon-site/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteOpenDataRoute = AppMonSiteOpenDataRouteImport.update({
  id: '/mon-site/open-data',
  path: '/mon-site/open-data',
  getParentRoute: () => AppRoute,
} as any)
const AppMonSiteReseauxRoute = AppMonSiteReseauxRouteImport.update({
  id: '/mon-site/reseaux',
  path: '/mon-site/reseaux',
  getParentRoute: () => AppRoute,
} as any)
const AppPagesDocumentIdRoute = AppPagesDocumentIdRouteImport.update({
  id: '/pages_/$documentId',
  path: '/pages/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const PlateformeCommunesDocumentIdRoute =
  PlateformeCommunesDocumentIdRouteImport.update({
    id: '/communes/$documentId',
    path: '/communes/$documentId',
    getParentRoute: () => PlateformeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/assistant': typeof AssistantRoute
  '/communes': typeof CommunesRoute
  '/connexion': typeof ConnexionRoute
  '/invitation': typeof InvitationRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/plateforme': typeof PlateformeRouteWithChildren
  '/actualites': typeof AppActualitesRoute
  '/agenda': typeof AppAgendaRoute
  '/alertes': typeof AppAlertesRoute
  '/associations': typeof AppAssociationsRoute
  '/cantine': typeof AppCantineRoute
  '/composants': typeof AppComposantsRoute
  '/conformite': typeof AppConformiteRoute
  '/dechets': typeof AppDechetsRoute
  '/documents': typeof AppDocumentsRoute
  '/editeur-de-blocs': typeof AppEditeurDeBlocsRoute
  '/equipe': typeof AppEquipeRoute
  '/journal': typeof AppJournalRoute
  '/mediatheque': typeof AppMediathequeRoute
  '/messages': typeof AppMessagesRoute
  '/mise-en-ligne': typeof AppMiseEnLigneRoute
  '/mon-compte': typeof AppMonCompteRoute
  '/newsletter': typeof AppNewsletterRoute
  '/pages': typeof AppPagesRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/plateforme/journal': typeof PlateformeJournalRoute
  '/plateforme/statistiques': typeof PlateformeStatistiquesRoute
  '/plateforme/utilisateurs': typeof PlateformeUtilisateursRoute
  '/plateforme/': typeof PlateformeIndexRoute
  '/actualites/$documentId': typeof AppActualitesDocumentIdRoute
  '/agenda/$documentId': typeof AppAgendaDocumentIdRoute
  '/alertes/$documentId': typeof AppAlertesDocumentIdRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/mon-site/accessibilite': typeof AppMonSiteAccessibiliteRoute
  '/mon-site/accueil': typeof AppMonSiteAccueilRoute
  '/mon-site/apparence': typeof AppMonSiteApparenceRoute
  '/mon-site/demarches': typeof AppMonSiteDemarchesRoute
  '/mon-site/informations': typeof AppMonSiteInformationsRoute
  '/mon-site/legal': typeof AppMonSiteLegalRoute
  '/mon-site/menu': typeof AppMonSiteMenuRoute
  '/mon-site/open-data': typeof AppMonSiteOpenDataRoute
  '/mon-site/reseaux': typeof AppMonSiteReseauxRoute
  '/pages/$documentId': typeof AppPagesDocumentIdRoute
  '/plateforme/communes/$documentId': typeof PlateformeCommunesDocumentIdRoute
}
export interface FileRoutesByTo {
  '/assistant': typeof AssistantRoute
  '/communes': typeof CommunesRoute
  '/connexion': typeof ConnexionRoute
  '/invitation': typeof InvitationRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/actualites': typeof AppActualitesRoute
  '/agenda': typeof AppAgendaRoute
  '/alertes': typeof AppAlertesRoute
  '/associations': typeof AppAssociationsRoute
  '/cantine': typeof AppCantineRoute
  '/composants': typeof AppComposantsRoute
  '/conformite': typeof AppConformiteRoute
  '/dechets': typeof AppDechetsRoute
  '/documents': typeof AppDocumentsRoute
  '/editeur-de-blocs': typeof AppEditeurDeBlocsRoute
  '/equipe': typeof AppEquipeRoute
  '/journal': typeof AppJournalRoute
  '/mediatheque': typeof AppMediathequeRoute
  '/messages': typeof AppMessagesRoute
  '/mise-en-ligne': typeof AppMiseEnLigneRoute
  '/mon-compte': typeof AppMonCompteRoute
  '/newsletter': typeof AppNewsletterRoute
  '/pages': typeof AppPagesRoute
  '/utilisateurs': typeof AppUtilisateursRoute
  '/plateforme/journal': typeof PlateformeJournalRoute
  '/plateforme/statistiques': typeof PlateformeStatistiquesRoute
  '/plateforme/utilisateurs': typeof PlateformeUtilisateursRoute
  '/': typeof AppIndexRoute
  '/plateforme': typeof PlateformeIndexRoute
  '/actualites/$documentId': typeof AppActualitesDocumentIdRoute
  '/agenda/$documentId': typeof AppAgendaDocumentIdRoute
  '/alertes/$documentId': typeof AppAlertesDocumentIdRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/mon-site/accessibilite': typeof AppMonSiteAccessibiliteRoute
  '/mon-site/accueil': typeof AppMonSiteAccueilRoute
  '/mon-site/apparence': typeof AppMonSiteApparenceRoute
  '/mon-site/demarches': typeof AppMonSiteDemarchesRoute
  '/mon-site/informations': typeof AppMonSiteInformationsRoute
  '/mon-site/legal': typeof AppMonSiteLegalRoute
  '/mon-site/menu': typeof AppMonSiteMenuRoute
  '/mon-site/open-data': typeof AppMonSiteOpenDataRoute
  '/mon-site/reseaux': typeof AppMonSiteReseauxRoute
  '/pages/$documentId': typeof AppPagesDocumentIdRoute
  '/plateforme/communes/$documentId': typeof PlateformeCommunesDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/communes': typeof CommunesRoute
  '/connexion': typeof ConnexionRoute
  '/invitation': typeof InvitationRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/plateforme': typeof PlateformeRouteWithChildren
  '/_app/actualites': typeof AppActualitesRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/alertes': typeof AppAlertesRoute
  '/_app/associations': typeof AppAssociationsRoute
  '/_app/cantine': typeof AppCantineRoute
  '/_app/composants': typeof AppComposantsRoute
  '/_app/conformite': typeof AppConformiteRoute
  '/_app/dechets': typeof AppDechetsRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/editeur-de-blocs': typeof AppEditeurDeBlocsRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/mediatheque': typeof AppMediathequeRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/mise-en-ligne': typeof AppMiseEnLigneRoute
  '/_app/mon-compte': typeof AppMonCompteRoute
  '/_app/newsletter': typeof AppNewsletterRoute
  '/_app/pages': typeof AppPagesRoute
  '/_app/utilisateurs': typeof AppUtilisateursRoute
  '/plateforme/journal': typeof PlateformeJournalRoute
  '/plateforme/statistiques': typeof PlateformeStatistiquesRoute
  '/plateforme/utilisateurs': typeof PlateformeUtilisateursRoute
  '/_app/': typeof AppIndexRoute
  '/plateforme/': typeof PlateformeIndexRoute
  '/_app/actualites_/$documentId': typeof AppActualitesDocumentIdRoute
  '/_app/agenda_/$documentId': typeof AppAgendaDocumentIdRoute
  '/_app/alertes_/$documentId': typeof AppAlertesDocumentIdRoute
  '/_app/documents_/$documentId': typeof AppDocumentsDocumentIdRoute
  '/_app/mon-site/accessibilite': typeof AppMonSiteAccessibiliteRoute
  '/_app/mon-site/accueil': typeof AppMonSiteAccueilRoute
  '/_app/mon-site/apparence': typeof AppMonSiteApparenceRoute
  '/_app/mon-site/demarches': typeof AppMonSiteDemarchesRoute
  '/_app/mon-site/informations': typeof AppMonSiteInformationsRoute
  '/_app/mon-site/legal': typeof AppMonSiteLegalRoute
  '/_app/mon-site/menu': typeof AppMonSiteMenuRoute
  '/_app/mon-site/open-data': typeof AppMonSiteOpenDataRoute
  '/_app/mon-site/reseaux': typeof AppMonSiteReseauxRoute
  '/_app/pages_/$documentId': typeof AppPagesDocumentIdRoute
  '/plateforme/communes/$documentId': typeof PlateformeCommunesDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/communes'
    | '/connexion'
    | '/invitation'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/plateforme'
    | '/actualites'
    | '/agenda'
    | '/alertes'
    | '/associations'
    | '/cantine'
    | '/composants'
    | '/conformite'
    | '/dechets'
    | '/documents'
    | '/editeur-de-blocs'
    | '/equipe'
    | '/journal'
    | '/mediatheque'
    | '/messages'
    | '/mise-en-ligne'
    | '/mon-compte'
    | '/newsletter'
    | '/pages'
    | '/utilisateurs'
    | '/plateforme/journal'
    | '/plateforme/statistiques'
    | '/plateforme/utilisateurs'
    | '/plateforme/'
    | '/actualites/$documentId'
    | '/agenda/$documentId'
    | '/alertes/$documentId'
    | '/documents/$documentId'
    | '/mon-site/accessibilite'
    | '/mon-site/accueil'
    | '/mon-site/apparence'
    | '/mon-site/demarches'
    | '/mon-site/informations'
    | '/mon-site/legal'
    | '/mon-site/menu'
    | '/mon-site/open-data'
    | '/mon-site/reseaux'
    | '/pages/$documentId'
    | '/plateforme/communes/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assistant'
    | '/communes'
    | '/connexion'
    | '/invitation'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/actualites'
    | '/agenda'
    | '/alertes'
    | '/associations'
    | '/cantine'
    | '/composants'
    | '/conformite'
    | '/dechets'
    | '/documents'
    | '/editeur-de-blocs'
    | '/equipe'
    | '/journal'
    | '/mediatheque'
    | '/messages'
    | '/mise-en-ligne'
    | '/mon-compte'
    | '/newsletter'
    | '/pages'
    | '/utilisateurs'
    | '/plateforme/journal'
    | '/plateforme/statistiques'
    | '/plateforme/utilisateurs'
    | '/'
    | '/plateforme'
    | '/actualites/$documentId'
    | '/agenda/$documentId'
    | '/alertes/$documentId'
    | '/documents/$documentId'
    | '/mon-site/accessibilite'
    | '/mon-site/accueil'
    | '/mon-site/apparence'
    | '/mon-site/demarches'
    | '/mon-site/informations'
    | '/mon-site/legal'
    | '/mon-site/menu'
    | '/mon-site/open-data'
    | '/mon-site/reseaux'
    | '/pages/$documentId'
    | '/plateforme/communes/$documentId'
  id:
    | '__root__'
    | '/_app'
    | '/assistant'
    | '/communes'
    | '/connexion'
    | '/invitation'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/plateforme'
    | '/_app/actualites'
    | '/_app/agenda'
    | '/_app/alertes'
    | '/_app/associations'
    | '/_app/cantine'
    | '/_app/composants'
    | '/_app/conformite'
    | '/_app/dechets'
    | '/_app/documents'
    | '/_app/editeur-de-blocs'
    | '/_app/equipe'
    | '/_app/journal'
    | '/_app/mediatheque'
    | '/_app/messages'
    | '/_app/mise-en-ligne'
    | '/_app/mon-compte'
    | '/_app/newsletter'
    | '/_app/pages'
    | '/_app/utilisateurs'
    | '/plateforme/journal'
    | '/plateforme/statistiques'
    | '/plateforme/utilisateurs'
    | '/_app/'
    | '/plateforme/'
    | '/_app/actualites_/$documentId'
    | '/_app/agenda_/$documentId'
    | '/_app/alertes_/$documentId'
    | '/_app/documents_/$documentId'
    | '/_app/mon-site/accessibilite'
    | '/_app/mon-site/accueil'
    | '/_app/mon-site/apparence'
    | '/_app/mon-site/demarches'
    | '/_app/mon-site/informations'
    | '/_app/mon-site/legal'
    | '/_app/mon-site/menu'
    | '/_app/mon-site/open-data'
    | '/_app/mon-site/reseaux'
    | '/_app/pages_/$documentId'
    | '/plateforme/communes/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  CommunesRoute: typeof CommunesRoute
  ConnexionRoute: typeof ConnexionRoute
  InvitationRoute: typeof InvitationRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NouveauMotDePasseRoute: typeof NouveauMotDePasseRoute
  PlateformeRoute: typeof PlateformeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communes': {
      id: '/communes'
      path: '/communes'
      fullPath: '/communes'
      preLoaderRoute: typeof CommunesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveau-mot-de-passe': {
      id: '/nouveau-mot-de-passe'
      path: '/nouveau-mot-de-passe'
      fullPath: '/nouveau-mot-de-passe'
      preLoaderRoute: typeof NouveauMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plateforme': {
      id: '/plateforme'
      path: '/plateforme'
      fullPath: '/plateforme'
      preLoaderRoute: typeof PlateformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actualites': {
      id: '/_app/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof AppActualitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertes': {
      id: '/_app/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AppAlertesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/associations': {
      id: '/_app/associations'
      path: '/associations'
      fullPath: '/associations'
      preLoaderRoute: typeof AppAssociationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cantine': {
      id: '/_app/cantine'
      path: '/cantine'
      fullPath: '/cantine'
      preLoaderRoute: typeof AppCantineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/composants': {
      id: '/_app/composants'
      path: '/composants'
      fullPath: '/composants'
      preLoaderRoute: typeof AppComposantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conformite': {
      id: '/_app/conformite'
      path: '/conformite'
      fullPath: '/conformite'
      preLoaderRoute: typeof AppConformiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dechets': {
      id: '/_app/dechets'
      path: '/dechets'
      fullPath: '/dechets'
      preLoaderRoute: typeof AppDechetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editeur-de-blocs': {
      id: '/_app/editeur-de-blocs'
      path: '/editeur-de-blocs'
      fullPath: '/editeur-de-blocs'
      preLoaderRoute: typeof AppEditeurDeBlocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mediatheque': {
      id: '/_app/mediatheque'
      path: '/mediatheque'
      fullPath: '/mediatheque'
      preLoaderRoute: typeof AppMediathequeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mise-en-ligne': {
      id: '/_app/mise-en-ligne'
      path: '/mise-en-ligne'
      fullPath: '/mise-en-ligne'
      preLoaderRoute: typeof AppMiseEnLigneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-compte': {
      id: '/_app/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AppMonCompteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newsletter': {
      id: '/_app/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof AppNewsletterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pages': {
      id: '/_app/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AppPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilisateurs': {
      id: '/_app/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AppUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/plateforme/': {
      id: '/plateforme/'
      path: '/'
      fullPath: '/plateforme/'
      preLoaderRoute: typeof PlateformeIndexRouteImport
      parentRoute: typeof PlateformeRoute
    }
    '/plateforme/journal': {
      id: '/plateforme/journal'
      path: '/journal'
      fullPath: '/plateforme/journal'
      preLoaderRoute: typeof PlateformeJournalRouteImport
      parentRoute: typeof PlateformeRoute
    }
    '/plateforme/statistiques': {
      id: '/plateforme/statistiques'
      path: '/statistiques'
      fullPath: '/plateforme/statistiques'
      preLoaderRoute: typeof PlateformeStatistiquesRouteImport
      parentRoute: typeof PlateformeRoute
    }
    '/plateforme/utilisateurs': {
      id: '/plateforme/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/plateforme/utilisateurs'
      preLoaderRoute: typeof PlateformeUtilisateursRouteImport
      parentRoute: typeof PlateformeRoute
    }
    '/_app/actualites_/$documentId': {
      id: '/_app/actualites_/$documentId'
      path: '/actualites/$documentId'
      fullPath: '/actualites/$documentId'
      preLoaderRoute: typeof AppActualitesDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda_/$documentId': {
      id: '/_app/agenda_/$documentId'
      path: '/agenda/$documentId'
      fullPath: '/agenda/$documentId'
      preLoaderRoute: typeof AppAgendaDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertes_/$documentId': {
      id: '/_app/alertes_/$documentId'
      path: '/alertes/$documentId'
      fullPath: '/alertes/$documentId'
      preLoaderRoute: typeof AppAlertesDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents_/$documentId': {
      id: '/_app/documents_/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/accessibilite': {
      id: '/_app/mon-site/accessibilite'
      path: '/mon-site/accessibilite'
      fullPath: '/mon-site/accessibilite'
      preLoaderRoute: typeof AppMonSiteAccessibiliteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/accueil': {
      id: '/_app/mon-site/accueil'
      path: '/mon-site/accueil'
      fullPath: '/mon-site/accueil'
      preLoaderRoute: typeof AppMonSiteAccueilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/apparence': {
      id: '/_app/mon-site/apparence'
      path: '/mon-site/apparence'
      fullPath: '/mon-site/apparence'
      preLoaderRoute: typeof AppMonSiteApparenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/demarches': {
      id: '/_app/mon-site/demarches'
      path: '/mon-site/demarches'
      fullPath: '/mon-site/demarches'
      preLoaderRoute: typeof AppMonSiteDemarchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/informations': {
      id: '/_app/mon-site/informations'
      path: '/mon-site/informations'
      fullPath: '/mon-site/informations'
      preLoaderRoute: typeof AppMonSiteInformationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/legal': {
      id: '/_app/mon-site/legal'
      path: '/mon-site/legal'
      fullPath: '/mon-site/legal'
      preLoaderRoute: typeof AppMonSiteLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/menu': {
      id: '/_app/mon-site/menu'
      path: '/mon-site/menu'
      fullPath: '/mon-site/menu'
      preLoaderRoute: typeof AppMonSiteMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/open-data': {
      id: '/_app/mon-site/open-data'
      path: '/mon-site/open-data'
      fullPath: '/mon-site/open-data'
      preLoaderRoute: typeof AppMonSiteOpenDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-site/reseaux': {
      id: '/_app/mon-site/reseaux'
      path: '/mon-site/reseaux'
      fullPath: '/mon-site/reseaux'
      preLoaderRoute: typeof AppMonSiteReseauxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pages_/$documentId': {
      id: '/_app/pages_/$documentId'
      path: '/pages/$documentId'
      fullPath: '/pages/$documentId'
      preLoaderRoute: typeof AppPagesDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/plateforme/communes/$documentId': {
      id: '/plateforme/communes/$documentId'
      path: '/communes/$documentId'
      fullPath: '/plateforme/communes/$documentId'
      preLoaderRoute: typeof PlateformeCommunesDocumentIdRouteImport
      parentRoute: typeof PlateformeRoute
    }
  }
}

interface AppRouteChildren {
  AppActualitesRoute: typeof AppActualitesRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppAlertesRoute: typeof AppAlertesRoute
  AppAssociationsRoute: typeof AppAssociationsRoute
  AppCantineRoute: typeof AppCantineRoute
  AppComposantsRoute: typeof AppComposantsRoute
  AppConformiteRoute: typeof AppConformiteRoute
  AppDechetsRoute: typeof AppDechetsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEditeurDeBlocsRoute: typeof AppEditeurDeBlocsRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMediathequeRoute: typeof AppMediathequeRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMiseEnLigneRoute: typeof AppMiseEnLigneRoute
  AppMonCompteRoute: typeof AppMonCompteRoute
  AppNewsletterRoute: typeof AppNewsletterRoute
  AppPagesRoute: typeof AppPagesRoute
  AppUtilisateursRoute: typeof AppUtilisateursRoute
  AppIndexRoute: typeof AppIndexRoute
  AppActualitesDocumentIdRoute: typeof AppActualitesDocumentIdRoute
  AppAgendaDocumentIdRoute: typeof AppAgendaDocumentIdRoute
  AppAlertesDocumentIdRoute: typeof AppAlertesDocumentIdRoute
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppMonSiteAccessibiliteRoute: typeof AppMonSiteAccessibiliteRoute
  AppMonSiteAccueilRoute: typeof AppMonSiteAccueilRoute
  AppMonSiteApparenceRoute: typeof AppMonSiteApparenceRoute
  AppMonSiteDemarchesRoute: typeof AppMonSiteDemarchesRoute
  AppMonSiteInformationsRoute: typeof AppMonSiteInformationsRoute
  AppMonSiteLegalRoute: typeof AppMonSiteLegalRoute
  AppMonSiteMenuRoute: typeof AppMonSiteMenuRoute
  AppMonSiteOpenDataRoute: typeof AppMonSiteOpenDataRoute
  AppMonSiteReseauxRoute: typeof AppMonSiteReseauxRoute
  AppPagesDocumentIdRoute: typeof AppPagesDocumentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActualitesRoute: AppActualitesRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppAlertesRoute: AppAlertesRoute,
  AppAssociationsRoute: AppAssociationsRoute,
  AppCantineRoute: AppCantineRoute,
  AppComposantsRoute: AppComposantsRoute,
  AppConformiteRoute: AppConformiteRoute,
  AppDechetsRoute: AppDechetsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEditeurDeBlocsRoute: AppEditeurDeBlocsRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppJournalRoute: AppJournalRoute,
  AppMediathequeRoute: AppMediathequeRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMiseEnLigneRoute: AppMiseEnLigneRoute,
  AppMonCompteRoute: AppMonCompteRoute,
  AppNewsletterRoute: AppNewsletterRoute,
  AppPagesRoute: AppPagesRoute,
  AppUtilisateursRoute: AppUtilisateursRoute,
  AppIndexRoute: AppIndexRoute,
  AppActualitesDocumentIdRoute: AppActualitesDocumentIdRoute,
  AppAgendaDocumentIdRoute: AppAgendaDocumentIdRoute,
  AppAlertesDocumentIdRoute: AppAlertesDocumentIdRoute,
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppMonSiteAccessibiliteRoute: AppMonSiteAccessibiliteRoute,
  AppMonSiteAccueilRoute: AppMonSiteAccueilRoute,
  AppMonSiteApparenceRoute: AppMonSiteApparenceRoute,
  AppMonSiteDemarchesRoute: AppMonSiteDemarchesRoute,
  AppMonSiteInformationsRoute: AppMonSiteInformationsRoute,
  AppMonSiteLegalRoute: AppMonSiteLegalRoute,
  AppMonSiteMenuRoute: AppMonSiteMenuRoute,
  AppMonSiteOpenDataRoute: AppMonSiteOpenDataRoute,
  AppMonSiteReseauxRoute: AppMonSiteReseauxRoute,
  AppPagesDocumentIdRoute: AppPagesDocumentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlateformeRouteChildren {
  PlateformeJournalRoute: typeof PlateformeJournalRoute
  PlateformeStatistiquesRoute: typeof PlateformeStatistiquesRoute
  PlateformeUtilisateursRoute: typeof PlateformeUtilisateursRoute
  PlateformeIndexRoute: typeof PlateformeIndexRoute
  PlateformeCommunesDocumentIdRoute: typeof PlateformeCommunesDocumentIdRoute
}

const PlateformeRouteChildren: PlateformeRouteChildren = {
  PlateformeJournalRoute: PlateformeJournalRoute,
  PlateformeStatistiquesRoute: PlateformeStatistiquesRoute,
  PlateformeUtilisateursRoute: PlateformeUtilisateursRoute,
  PlateformeIndexRoute: PlateformeIndexRoute,
  PlateformeCommunesDocumentIdRoute: PlateformeCommunesDocumentIdRoute,
}

const PlateformeRouteWithChildren = PlateformeRoute._addFileChildren(
  PlateformeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AssistantRoute: AssistantRoute,
  CommunesRoute: CommunesRoute,
  ConnexionRoute: ConnexionRoute,
  InvitationRoute: InvitationRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NouveauMotDePasseRoute: NouveauMotDePasseRoute,
  PlateformeRoute: PlateformeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
